# --- Базовая информация ---
spring.application.name=aesty-messenger

# --- Настройки БД ---
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Настройки Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

# --- Настройки сессий ---
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=SPRING_SESSION

# --- Безопасность (JWT) ---
jwt.secret=${JWT_SECRET:A71E47478999780BE24B9E99EB94DF3FFC734BE72F9C4844067D31F339BF74D4}
jwt.expiration=604800

# --- Настройки почты (Яндекс) ---
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=${bebrsosaevitch@yandex.ru}
spring.mail.password=${jbhqlhkicffbsocp}
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru
app.email.url=${APP_EMAIL_URL:http://localhost:8080/confirm-account}

# --- Google OAuth2 ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# --- Прочее ---
spring.thymeleaf.cache=false